version: "2"
services:
  loadbalancer:
    image: johscheuer/docker-nginx-loadbalancer:v1
    container_name: loadbalancer
    ports:
      - "80:80"
    environment:
      - APP_NAME=todo-app-web
      - CONSUL_URL=${CLUSTER_STORE_IP}:8500
    depends_on:
      - todo-app
    networks:
      - front

  todo-app:
    image: johscheuer/todo-app-web:v2
    ports:
     - "3000"
    depends_on:
     - redis-master
     - redis-slave
    networks:
      - front
      - redis

  redis-slave:
    image: johscheuer/redis-slave:v1
    depends_on:
     - redis-master
    networks:
     - redis

  redis-master:
    image: redis:3-alpine
    networks:
     - redis

networks:
  front:
    driver: overlay
  redis:
    driver: overlay
